language: go

sudo: required
dist: trusty

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: 1.7.x
    - go: 1.8.x
    - go: master
    - go: tip

cache: apt

install:
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify

script:
  - make travis

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
